sudo: required
services:
- docker
language: bash
script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker build -t ansi/feelflight-11-3-interaction:latest .
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker push ansi/feelflight-11-3-interaction:latest
